version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata: